GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.05   # 当设置的目的地被障碍物占据时,需要以该参数为半径寻找到最近的点作为新目的地点.
  use_dijkstra: true    # 设置为true,将使用dijkstra算法,否则使用A*算法.
  use_quadratic: true     #设置为true,将使用二次函数近似函数; false则使用更加简单的计算方式,这样节省硬件计算资源.
  use_grid_path: false    # 如果设置为true,则会规划一条沿着网格边界的路径,偏向于直线穿越网格,否则将使用梯度下降算法,路径更为光滑点
  outline_map: false
  old_navfn_behavior: false

  visualize_potential: false
  publish_potential: true

  lethal_cost: 253   # 致命代价值,默认是设置为253,可以动态来配置该参数.
  neutral_cost: 50  #中等代价值,默认设置是50,可以动态配置该参数.
  cost_factor: 3.0  # 代价地图与每个代价值相乘的因子.

  orientation_mode: 0
  orientation_window_size: 1