global_costmap:
  global_frame: map   #全局代价地图运行的坐标系
  robot_base_frame: base_footprint
  transform_tolerance: 0.5  # 坐标系之间的转换可以忍受的最大延时

  update_frequency: 10.0   #全局代价地图更新频率，一般全局代价地图更新频率设置的比较小，因为不需要那么多的更新，基本没有很大的变动在比赛中，默认为10，建议可以改小一点
  publish_frequency: 10.0  # 与上面的更新对应，值应该是一样的为好
  #在global_costmap中使用下面三个插件来融合三个不同图层，分别是static_layer、obstacle_layer和inflation_layer，合成一个master_layer来进行全局路径规划。
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
