local_costmap:
  global_frame: odom
  # global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

  update_frequency: 5.5  #局部代价地图的更新频率;
  publish_frequency: 5.0  # 局部代价地图的发布频率;
 # update_frequency: 4.0
  #publish_frequency: 4.0
  rolling_window: true   # 使用滚动窗口，始终保持机器人在当前局部地图的中心位置;
  width: 3
  height: 3
  resolution: 0.05    # 分辨率

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
