shutdown_costmaps: false   #当move_base在不活动状态时,是否关掉costmap
#机器人必须移动多远（以米计）才能被视为不摆动。
#如果出现摆动则说明全局规划失败，那么将在超时后执行恢复模块
oscillation_distance: 0.2  #来回运动在多大距离以上不会被认为是振荡
oscillation_timeout: 10.0  #执行修复机制前,允许振荡的时长

controller_frequency: 8.0   #向底盘控制移动话题cmd_vel发送命令的频率.
controller_patience: 5.0   #在空间清理操作执行前,控制器花多长时间等有效控制下发.

planner_frequency: 5.0   #全局规划操作的执行频率.如果设置为0.0,则全局规划器仅在接收到新的目标点或者局部规划器报告路径堵塞时才会重新执行规划操作.
planner_patience: 3.0      #在空间 清理操作执行前,留给规划器多长时间来找出一条有效规划.
max_planning_retries: -1   #在执行恢复行为之前允许计划重试的次数.默认为-1，表示全局规划失败后立即执行恢复模块。
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/TebLocalPlannerROS"
